INSERT INTO Coin (name, ticker) VALUES ('Bitcoin', 'BTC');
INSERT INTO Coin (name, ticker) VALUES ('Ethereum', 'ETH');
INSERT INTO Coin (name, ticker) VALUES ('BNB', 'BNB');
INSERT INTO Coin (name, ticker) VALUES ('USD Coin', 'USDC');
INSERT INTO Coin (name, ticker) VALUES ('XRP', 'XRP');
INSERT INTO Coin (name, ticker) VALUES ('Cardano', 'ADA');
INSERT INTO Coin (name, ticker) VALUES ('Dogecoin', 'DOGE');
INSERT INTO Coin (name, ticker) VALUES ('Polygon', 'POL');
INSERT INTO Coin (name, ticker) VALUES ('Solana', 'SOL');
INSERT INTO Coin (name, ticker) VALUES ('Polkadot', 'DOT');
INSERT INTO Coin (name, ticker) VALUES ('Litecoin', 'LTC');
INSERT INTO Coin (name, ticker) VALUES ('Shiba Inu', 'SHIB');
INSERT INTO Coin (name, ticker) VALUES ('Avalanche', 'AVAX');
INSERT INTO Coin (name, ticker) VALUES ('Wrapped Bitcoin', 'WBTC');
INSERT INTO Coin (name, ticker) VALUES ('TRON', 'TRX');
INSERT INTO Coin (name, ticker) VALUES ('Chainlink', 'LINK');
INSERT INTO Coin (name, ticker) VALUES ('Cosmos', 'ATOM');
INSERT INTO Coin (name, ticker) VALUES ('Ethereum Classic', 'ETC');
INSERT INTO Coin (name, ticker) VALUES ('Stellar', 'XLM');
INSERT INTO Coin (name, ticker) VALUES ('Bitcoin Cash', 'BCH');
INSERT INTO Coin (name, ticker) VALUES ('Internet Computer', 'ICP');
INSERT INTO Coin (name, ticker) VALUES ('Filecoin', 'FIL');
INSERT INTO Coin (name, ticker) VALUES ('Lido DAO', 'LDO');
INSERT INTO Coin (name, ticker) VALUES ('Hedera', 'HBAR');
INSERT INTO Coin (name, ticker) VALUES ('Arbitrum', 'ARB');
INSERT INTO Coin (name, ticker) VALUES ('Aptos', 'APT');
INSERT INTO Coin (name, ticker) VALUES ('Quant', 'QNT');
INSERT INTO Coin (name, ticker) VALUES ('VeChain', 'VET');
INSERT INTO Coin (name, ticker) VALUES ('NEAR Protocol', 'NEAR');
INSERT INTO Coin (name, ticker) VALUES ('Optimism', 'OP');
INSERT INTO Coin (name, ticker) VALUES ('Algorand', 'ALGO');
INSERT INTO Coin (name, ticker) VALUES ('The Graph', 'GRT');
INSERT INTO Coin (name, ticker) VALUES ('Stacks', 'STX');
INSERT INTO Coin (name, ticker) VALUES ('Aave', 'AAVE');
INSERT INTO Coin (name, ticker) VALUES ('EOS', 'EOS');
INSERT INTO Coin (name, ticker) VALUES ('MultiversX', 'EGLD');
INSERT INTO Coin (name, ticker) VALUES ('Theta Network', 'THETA');
INSERT INTO Coin (name, ticker) VALUES ('Tezos', 'XTZ');
INSERT INTO Coin (name, ticker) VALUES ('Fantom', 'FTM');
INSERT INTO Coin (name, ticker) VALUES ('Decentraland', 'MANA');
INSERT INTO Coin (name, ticker) VALUES ('Axie Infinity', 'AXS');
INSERT INTO Coin (name, ticker) VALUES ('Chiliz', 'CHZ');
INSERT INTO Coin (name, ticker) VALUES ('Injective', 'INJ');
INSERT INTO Coin (name, ticker) VALUES ('1inch', '1INCH');
INSERT INTO Coin (name, ticker) VALUES ('ApeCoin', 'APE');
INSERT INTO Coin (name, ticker) VALUES ('Basic Attention Token', 'BAT');
INSERT INTO Coin (name, ticker) VALUES ('Uniswap', 'UNI');