CREATE TABLE Holder
(
    id            INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name          VARCHAR,
    password_hash VARCHAR        NOT NULL,
    email         VARCHAR UNIQUE NOT NULL,
    avatar_url    VARCHAR
);

CREATE TABLE Coin
(
    id     INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name   VARCHAR NOT NULL UNIQUE,
    ticker VARCHAR NOT NULL UNIQUE
);

CREATE TABLE Portfolio
(
    id         SERIAL PRIMARY KEY,
    name       VARCHAR   NOT NULL,
    avatar     VARCHAR   NOT NULL,
    bg_color   VARCHAR   NOT NULL,
    holder_id  INT       NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (holder_id) REFERENCES Holder (id)
);

CREATE TYPE transaction_type AS ENUM ('SELL', 'BUY');

CREATE TABLE Transaction
(
    id             SERIAL PRIMARY KEY,
    type           transaction_type NOT NULL,
    amount         DECIMAL                  NOT NULL,
    coin_id        INT,
    price_per_unit DECIMAL,
    portfolio_id   INT,
    date           TIMESTAMPTZ              NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (coin_id) REFERENCES Coin (id),
    FOREIGN KEY (portfolio_id) REFERENCES Portfolio (id)
);

CREATE CAST (CHARACTER VARYING AS transaction_type) WITH INOUT AS IMPLICIT;
