CREATE SCHEMA IF NOT EXISTS hodlhub;

CREATE TABLE IF NOT EXISTS hodlhub.Holder
(
    id            INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name          VARCHAR,
    password_hash VARCHAR        NOT NULL,
    email         VARCHAR UNIQUE NOT NULL,
    avatar_url    VARCHAR
);

CREATE TABLE IF NOT EXISTS hodlhub.Email_verification
(
    id                INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    email             VARCHAR(255) NOT NULL UNIQUE,
    name              VARCHAR(255),
    encoded_password  VARCHAR(255) NOT NULL,
    verification_code VARCHAR(6)   NOT NULL,
    created_at        TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    expires_at        TIMESTAMP    NOT NULL
);

CREATE TABLE IF NOT EXISTS hodlhub.Coin
(
    id     INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name   VARCHAR NOT NULL UNIQUE,
    ticker VARCHAR NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS hodlhub.Portfolio
(
    id         SERIAL PRIMARY KEY,
    name       VARCHAR   NOT NULL,
    avatar     VARCHAR   NOT NULL,
    bg_color   VARCHAR   NOT NULL,
    holder_id  INT       NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (holder_id) REFERENCES hodlhub.Holder (id)
);

CREATE TYPE hodlhub.transaction_type AS ENUM ('SELL', 'BUY');

CREATE TABLE IF NOT EXISTS hodlhub.Transaction
(
    id             SERIAL PRIMARY KEY,
    type           hodlhub.transaction_type NOT NULL,
    amount         DECIMAL                  NOT NULL,
    coin_id        INT,
    price_per_unit DECIMAL,
    portfolio_id   INT,
    date           TIMESTAMPTZ              NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (coin_id) REFERENCES hodlhub.Coin (id),
    FOREIGN KEY (portfolio_id) REFERENCES hodlhub.Portfolio (id)
);

CREATE CAST (CHARACTER VARYING AS hodlhub.transaction_type) WITH INOUT AS IMPLICIT;

